In [1]:
import sys
sys.path.append("/Users/svaddadi/Documents/GitHub/")
import EGAT
from EGAT import src
from EGAT.src.utils.descriptors.egat.reactive import Reactive
from rdkit import Chem 

In [2]:
sample = '[C:1][c:2]1[c:3][c:4][c:5][c:6][c:7]1'
reactant = Chem.MolFromSmiles(sample)
R_bond_mat = Chem.GetAdjacencyMatrix(reactant, useBO=True)
print(R_bond_mat)


[[0.  1.  0.  0.  0.  0.  0. ]
 [1.  0.  1.5 0.  0.  0.  1.5]
 [0.  1.5 0.  1.5 0.  0.  0. ]
 [0.  0.  1.5 0.  1.5 0.  0. ]
 [0.  0.  0.  1.5 0.  1.5 0. ]
 [0.  0.  0.  0.  1.5 0.  1.5]
 [0.  1.5 0.  0.  0.  1.5 0. ]]


In [3]:
sample = '[CH3:1].[c:2]1[c:3][c:4][c:5][c:6][c:7]1'
product = Chem.MolFromSmiles(sample)
P_bond_mat = Chem.GetAdjacencyMatrix(product, useBO=True)
print(P_bond_mat)

[[0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  1.5 0.  0.  0.  1.5]
 [0.  1.5 0.  1.5 0.  0.  0. ]
 [0.  0.  1.5 0.  1.5 0.  0. ]
 [0.  0.  0.  1.5 0.  1.5 0. ]
 [0.  0.  0.  0.  1.5 0.  1.5]
 [0.  1.5 0.  0.  0.  1.5 0. ]]


In [4]:
E = ['C', 'C', 'C', 'C', 'C', 'C', 'C']

reactive = Reactive(E, R_bond_mat, P_bond_mat)
reactive.ReactiveAtoms()
reactive.bnfn()

In [5]:
attributes = [attr for attr in dir(reactive) if not callable(getattr(reactive, attr)) and not attr.startswith("__")]
for attr in attributes:
    value = getattr(reactive, attr)
    print(f"{attr}: {type(value)} = {value}")

attributes = [attr for attr in dir(reactive.bond) if not callable(getattr(reactive.bond, attr)) and not attr.startswith("__")]
for attr in attributes:
    value = getattr(reactive.bond, attr)
    print(f"{attr}: {type(value)} = {value}")

    


E: <class 'list'> = ['C', 'C', 'C', 'C', 'C', 'C', 'C']
Pbond_mat: <class 'numpy.ndarray'> = [[0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  1.5 0.  0.  0.  1.5]
 [0.  1.5 0.  1.5 0.  0.  0. ]
 [0.  0.  1.5 0.  1.5 0.  0. ]
 [0.  0.  0.  1.5 0.  1.5 0. ]
 [0.  0.  0.  0.  1.5 0.  1.5]
 [0.  1.5 0.  0.  0.  1.5 0. ]]
Rbond_mat: <class 'numpy.ndarray'> = [[0.  1.  0.  0.  0.  0.  0. ]
 [1.  0.  1.5 0.  0.  0.  1.5]
 [0.  1.5 0.  1.5 0.  0.  0. ]
 [0.  0.  1.5 0.  1.5 0.  0. ]
 [0.  0.  0.  1.5 0.  1.5 0. ]
 [0.  0.  0.  0.  1.5 0.  1.5]
 [0.  1.5 0.  0.  0.  1.5 0. ]]
bnfn: <class 'list'> = [1, 0]
bondmat_change: <class 'numpy.ndarray'> = [[ 0. -1.  0.  0.  0.  0.  0.]
 [-1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]]
broken: <class 'list'> = [(0, 1)]
change: <class 'list'> = [(0, 1)]
formed: <class 'list'> = []
ochange: <class 'list'> = []
ochangedown: <class