In [1]:
import sys
sys.path.append("/Users/svaddadi/Documents/GitHub/")
import EGAT
from EGAT import src
from EGAT.src.graph.base.base import BaseFeaturizer,BaseReactionParams
from EGAT.src.graph.base.component import BaseReactionComponentFeaturizer
from EGAT.src.graph.base.reaction import BaseReactionFeaturizer,ReactionBaseParams

In [2]:
params = BaseReactionParams()
params.acidbase = 'BL'
params.getradical = 'RDKit'
params.stereo_full = True
smiles = "CC(=O)C1=CC=C(C=C1)C(=O)O"

graph = BaseFeaturizer(smiles,params)



In [3]:
def printattributes(atr):
    attributes = [attr for attr in dir(atr) if not callable(getattr(atr, attr)) and not attr.startswith("__")]
    for attr in attributes:
        value = getattr(atr, attr)
        print(f"{attr}: {type(value)} = {value}")

    print ('There are {} attributes in the MolMatDesc class!'.format(len(attributes)))

printattributes(graph)

acid_sites: <class 'list'> = [11]
am_smiles: <class 'str'> = [C:1]([C:2](=[O:3])[c:4]1[c:5]([H:16])[c:6]([H:17])[c:7]([C:10](=[O:11])[O:12][H:20])[c:8]([H:18])[c:9]1[H:19])([H:13])([H:14])[H:15]
base_sites: <class 'list'> = [2, 10]
electroninfo: <class 'EGAT.src.utils.descriptors.egat.radicals.RDKElectronInfo'> = <EGAT.src.utils.descriptors.egat.radicals.RDKElectronInfo object at 0x103749d20>
matrixdescriptors: <class 'EGAT.src.utils.descriptors.egat.molmatdesc.MolMatDesc'> = <EGAT.src.utils.descriptors.egat.molmatdesc.MolMatDesc object at 0x103749f90>
params: <class 'EGAT.src.graph.base.base.BaseReactionParams'> = BaseReactionParams(getradical='RDKit', stereo_full=True, acidbase='BL')
pauling_dict: <class 'dict'> = {'H': 2.2, 'He': None, 'Li': 0.98, 'Be': 1.57, 'B': 2.04, 'C': 2.55, 'N': 3.04, 'O': 3.44, 'F': 3.98, 'Ne': None, 'Na': 0.93, 'Mg': 1.31, 'Al': 1.61, 'Si': 1.9, 'P': 2.19, 'S': 2.58, 'Cl': 3.16, 'Ar': None, 'K': 0.82, 'Ca': 1.0, 'Sc': 1.36, 'Ti': 1.54, 'V': 1.63, 'Cr': 1.66

In [4]:
params.acidbase = 'Lewis'
params.getradical = 'RDKit'
params.stereo_full = True
smiles = "CC(=O)C1=CC=C(C=C1)C(=O)O"

graph = BaseFeaturizer(smiles,params)
printattributes(graph)

acid_sites: <class 'list'> = [1, 3, 4, 5, 6, 7, 8, 9]
am_smiles: <class 'str'> = [C:1]([C:2](=[O:3])[c:4]1[c:5]([H:16])[c:6]([H:17])[c:7]([C:10](=[O:11])[O:12][H:20])[c:8]([H:18])[c:9]1[H:19])([H:13])([H:14])[H:15]
base_sites: <class 'list'> = [2, 10]
electroninfo: <class 'EGAT.src.utils.descriptors.egat.radicals.RDKElectronInfo'> = <EGAT.src.utils.descriptors.egat.radicals.RDKElectronInfo object at 0x32f510d90>
matrixdescriptors: <class 'EGAT.src.utils.descriptors.egat.molmatdesc.MolMatDesc'> = <EGAT.src.utils.descriptors.egat.molmatdesc.MolMatDesc object at 0x32f4b9540>
params: <class 'EGAT.src.graph.base.base.BaseReactionParams'> = BaseReactionParams(getradical='RDKit', stereo_full=True, acidbase='Lewis')
pauling_dict: <class 'dict'> = {'H': 2.2, 'He': None, 'Li': 0.98, 'Be': 1.57, 'B': 2.04, 'C': 2.55, 'N': 3.04, 'O': 3.44, 'F': 3.98, 'Ne': None, 'Na': 0.93, 'Mg': 1.31, 'Al': 1.61, 'Si': 1.9, 'P': 2.19, 'S': 2.58, 'Cl': 3.16, 'Ar': None, 'K': 0.82, 'Ca': 1.0, 'Sc': 1.36, 'Ti': 1.54

In [5]:
graph= BaseReactionComponentFeaturizer(smiles,params)
printattributes(graph)

acid_sites: <class 'list'> = [1, 3, 4, 5, 6, 7, 8, 9]
am_smiles: <class 'str'> = [C:1]([C:2](=[O:3])[c:4]1[c:5]([H:16])[c:6]([H:17])[c:7]([C:10](=[O:11])[O:12][H:20])[c:8]([H:18])[c:9]1[H:19])([H:13])([H:14])[H:15]
base_sites: <class 'list'> = [2, 10]
electroninfo: <class 'EGAT.src.utils.descriptors.egat.radicals.RDKElectronInfo'> = <EGAT.src.utils.descriptors.egat.radicals.RDKElectronInfo object at 0x32f510c10>
gs: <class 'numpy.ndarray'> = [[0. 1. 2. 2. 3. 4. 5. 4. 3. 6. 7. 7. 1. 1. 1. 4. 5. 5. 4. 8.]
 [1. 0. 1. 1. 2. 3. 4. 3. 2. 5. 6. 6. 2. 2. 2. 3. 4. 4. 3. 7.]
 [2. 1. 0. 2. 3. 4. 5. 4. 3. 6. 7. 7. 3. 3. 3. 4. 5. 5. 4. 8.]
 [2. 1. 2. 0. 1. 2. 3. 2. 1. 4. 5. 5. 3. 3. 3. 2. 3. 3. 2. 6.]
 [3. 2. 3. 1. 0. 1. 2. 3. 2. 3. 4. 4. 4. 4. 4. 1. 2. 4. 3. 5.]
 [4. 3. 4. 2. 1. 0. 1. 2. 3. 2. 3. 3. 5. 5. 5. 2. 1. 3. 4. 4.]
 [5. 4. 5. 3. 2. 1. 0. 1. 2. 1. 2. 2. 6. 6. 6. 3. 2. 2. 3. 3.]
 [4. 3. 4. 2. 3. 2. 1. 0. 1. 2. 3. 3. 5. 5. 5. 4. 3. 1. 2. 4.]
 [3. 2. 3. 1. 2. 3. 2. 1. 0. 3. 4. 4. 4. 4. 4. 3. 

In [6]:
sn1_reaction_smiles = "CC>>C.C"
print(f"SN1 Reaction SMILES: {sn1_reaction_smiles}")

params = ReactionBaseParams()
params.acidbase = 'BL'
params.getradical = 'RDKit'
params.stereo_full = True
smiles = "CC(=O)C1=CC=C(C=C1)C(=O)O"
graph = BaseReactionFeaturizer(sn1_reaction_smiles, params)

printattributes(graph)

SN1 Reaction SMILES: CC>>C.C
Reactant: CC, Product: C.C
<rdkit.Chem.rdchem.Mol object at 0x32f09a030> CC
<rdkit.Chem.rdchem.Mol object at 0x32f09a030> C.C
Reactant: [CH3:1][CH3:2], Product: [CH4:1].[CH4:2]
elementcheck: <class 'bool'> = False
mapper_condfidence: <class 'numpy.float64'> = 0.9295523445017015
params: <class 'EGAT.src.graph.base.reaction.ReactionBaseParams'> = ReactionBaseParams(mappingfunction='RXNMapper', totalmapping=True)
product: <class 'EGAT.src.graph.base.base.BaseFeaturizer'> = <EGAT.src.graph.base.base.BaseFeaturizer object at 0x32f77ff70>
reactant: <class 'EGAT.src.graph.base.base.BaseFeaturizer'> = <EGAT.src.graph.base.base.BaseFeaturizer object at 0x1035d6e60>
reaction: <class 'str'> = CC>>C.C
There are 6 attributes in the MolMatDesc class!


In [7]:
printattributes(graph.reactant)

acid_sites: <class 'list'> = []
am_smiles: <class 'str'> = [C:1]([C:2]([H:6])([H:7])[H:8])([H:3])([H:4])[H:5]
atom_features: <class 'NoneType'> = None
base_sites: <class 'list'> = []
bond_features: <class 'NoneType'> = None
electroninfo: <class 'EGAT.src.utils.descriptors.egat.radicals.RDKElectronInfo'> = <EGAT.src.utils.descriptors.egat.radicals.RDKElectronInfo object at 0x103748490>
matrixdescriptors: <class 'EGAT.src.utils.descriptors.egat.molmatdesc.MolMatDesc'> = <EGAT.src.utils.descriptors.egat.molmatdesc.MolMatDesc object at 0x32f48c880>
params: <class 'EGAT.src.graph.base.reaction.ReactionBaseParams'> = ReactionBaseParams(mappingfunction='RXNMapper', totalmapping=True)
pauling_dict: <class 'dict'> = {'H': 2.2, 'He': None, 'Li': 0.98, 'Be': 1.57, 'B': 2.04, 'C': 2.55, 'N': 3.04, 'O': 3.44, 'F': 3.98, 'Ne': None, 'Na': 0.93, 'Mg': 1.31, 'Al': 1.61, 'Si': 1.9, 'P': 2.19, 'S': 2.58, 'Cl': 3.16, 'Ar': None, 'K': 0.82, 'Ca': 1.0, 'Sc': 1.36, 'Ti': 1.54, 'V': 1.63, 'Cr': 1.66, 'Mn': 1

In [8]:
printattributes(graph.product)

acid_sites: <class 'list'> = []
am_smiles: <class 'str'> = [C:1]([H:3])([H:4])([H:5])[H:6].[C:2]([H:7])([H:8])([H:9])[H:10]
atom_features: <class 'NoneType'> = None
base_sites: <class 'list'> = []
bond_features: <class 'NoneType'> = None
electroninfo: <class 'EGAT.src.utils.descriptors.egat.radicals.RDKElectronInfo'> = <EGAT.src.utils.descriptors.egat.radicals.RDKElectronInfo object at 0x32e128550>
matrixdescriptors: <class 'EGAT.src.utils.descriptors.egat.molmatdesc.MolMatDesc'> = <EGAT.src.utils.descriptors.egat.molmatdesc.MolMatDesc object at 0x32e128580>
params: <class 'EGAT.src.graph.base.reaction.ReactionBaseParams'> = ReactionBaseParams(mappingfunction='RXNMapper', totalmapping=True)
pauling_dict: <class 'dict'> = {'H': 2.2, 'He': None, 'Li': 0.98, 'Be': 1.57, 'B': 2.04, 'C': 2.55, 'N': 3.04, 'O': 3.44, 'F': 3.98, 'Ne': None, 'Na': 0.93, 'Mg': 1.31, 'Al': 1.61, 'Si': 1.9, 'P': 2.19, 'S': 2.58, 'Cl': 3.16, 'Ar': None, 'K': 0.82, 'Ca': 1.0, 'Sc': 1.36, 'Ti': 1.54, 'V': 1.63, 'Cr':